version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /opt/recordings:/files
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=US/Chicago
      - TZ=America/Chicago
    ports:
      - 7000:80
      #- 49494:80
    restart: unless-stopped

  motion:
    build: motion_conf/
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8084:8084
      - 8085:8085
      - 8086:8086
      - 8087:8087
      - 8088:8088
    volumes: 
      - /opt/recordings:/recordings
      - ./motion_conf/motion.conf:/etc/motion/motion.conf
      - ./motion_conf/cam_conf:/etc/motion/conf.d
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=America/Chicago
      - TZ=America/Chicago
    restart: unless-stopped

  cctv:
    build: horrible_cctv/
    volumes:
      - ./horrible_cctv:/app
      - /opt/recordings:/recordings
    ports:
      - 80:80
    environment:
      - BASE_URL=http://192.168.1.69:7000/
      - TIME_OFFSET=5
    restart: unless-stopped
