version: '3'
services:
  nginx:
    image: tiangolo/nginx-rtmp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.key:/etc/nginx/server.key
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./html:/var/www
    ports:
      - 80:80
      - 1935:1935
    restart: always

  # Direct Camera Feeds
  drive_way:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg  -i rtsp://192.168.1.10:554/s0 -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/driveway
    restart: always
