version: '3'
services:
  dev_cam:
    build: ./camera
    #command: bash start_camera.sh 
    volumes:
      - ./camera:/app
      - ./sd_cam:/app/sd_cam
    environment:
      # URL with credentials to the camera stream
      - CAM_URL=rtsp://192.168.1.86:554/live/av0?user=admin&passwd=pylecam
      - CAM_NAME=Dining_Room

  dining_room_cam:
    build: ./camera
    #command: bash start_camera.sh 
    volumes:
      - ./camera:/app
      - ./sd_cam:/app/sd_cam
    environment:
      # URL with credentials to the camera stream
      - CAM_URL=rtsp://192.168.1.86:554/live/av0?user=admin&passwd=pylecam
      - CAM_NAME=Dining_Room

  living_room_cam:
    build: ./camera
    volumes:
      - ./camera:/app
      - ./sd_cam:/app/sd_cam
    environment:
      # URL with credentials to the camera stream
      - CAM_URL=rtsp://192.168.1.250:554/live/av0?user=admin&passwd=pylecam
      - CAM_NAME=Living_Room

  kitchen_cam:
    build: ./camera
    volumes:
      - ./camera:/app
      - ./sd_cam:/app/sd_cam
    environment:
      # URL with credentials to the camera stream
      - CAM_URL=rtsp://192.168.1.250:554/live/av0?user=admin&passwd=pylecam
      - CAM_NAME=Kitchen_Cam

  webapp:
    build: ./webapp
    volumes:
      - ./webapp:/app
      - ./sd_cam:/app/static/sd_cam
    ports:
      - 8080:80
