version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.key:/etc/nginx/server.key
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./html:/var/www
      # NGINX stores the tmp video files here
      - /opt/videos/dash:/videos/dash
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=US/Chicago
      - TZ=America/Chicago
    ports:
      - 80:80
      - 1935:1935
    restart: unless-stopped

  # Direct Camera Feeds
  living_room:
    image: jrottenberg/ffmpeg:latest
    volumes:
      - ./html/dash:/videos/dash
    entrypoint: |
        ffmpeg -i "rtsp://192.168.1.11:554/live/av1?user=admin&passwd=pylecam" -an -c:v copy -b:v 2000k -f dash -window_size 4 -extra_window_size 0 -min_seg_duration 2000000 -remove_at_exit 1 /videos/dash/living_room.mpd
    restart: unless-stopped
