version: '3'
services:
  nginx:
    image: tiangolo/nginx-rtmp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.key:/etc/nginx/server.key
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./html:/var/www
    ports:
      - 80:80
      - 1935:1935
    restart: always

  # Direct Camera Feeds
  drive_way:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg  -i rtsp://192.168.1.10:554/s0 -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/driveway
    restart: always

  frontyard:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg  -i rtsp://192.168.1.16/stream1 -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/frontyard
    restart: always

  backyard_porch:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg  -i rtsp://admin:yourmom%21@192.168.1.15:554/videoMain -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/backyard_porch
    restart: always

  backyard_fence:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg  -i rtsp://admin:yourmom%21@192.168.1.14:554/videoMain -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/backyard_fence

  living_room:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg  -i rtsp://192.168.1.12:554/live/av0?user=admin&passwd=pylecam -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/living_room
    restart: always

  dining_room:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg  -i rtsp://192.168.1.13:554/live/av0?user=admin&passwd=pylecam -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/dining_room
    restart: always

  kitchen:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg  -i rtsp://192.168.1.11:554/live/av0?user=admin&passwd=pylecam -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/kitchen
    restart: always

  garage:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg  -i rtsp://admin:yourmom%21@192.168.1.17:554/videoMain -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/garage
    restart: always
