version: '3'
services:
  nginx:
    image: tiangolo/nginx-rtmp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.key:/etc/nginx/server.key
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./html:/var/www
      # NGINX stores the tmp video files here
      - /opt/videos:/videos
      - /opt/recordings:/recordings
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=US/Chicago
      - TZ=America/Chicago
    ports:
      - 80:80
      - 1935:1935
    restart: unless-stopped

  # Direct Camera Feeds
  drive_way:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg  -analyzeduration 1000000 -probesize 1000000 -i rtsp://192.168.1.10:554/s0 -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/driveway
    restart: unless-stopped

  frontyard:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg -analyzeduration 1000000 -probesize 1000000 -i rtsp://192.168.1.16/stream1 -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/frontyard
    restart: unless-stopped

  backyard_porch:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg -analyzeduration 1000000 -probesize 1000000 -i rtsp://admin:yourmom%21@192.168.1.15:554/videoMain -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/backyard_porch
    restart: unless-stopped

  backyard_fence:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg -analyzeduration 1000000 -probesize 1000000 -i rtsp://admin:yourmom%21@192.168.1.14:554/videoMain -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/backyard_fence
    restart: unless-stopped

  living_room:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg  -analyzeduration 1000000 -probesize 1000000 -i rtsp://192.168.1.12:554/live/av0?user=admin&passwd=pylecam -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/living_room
    restart: unless-stopped

  dining_room:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg  -analyzeduration 1000000 -probesize 1000000 -i rtsp://192.168.1.13:554/live/av0?user=admin&passwd=pylecam -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/dining_room
    restart: unless-stopped

  kitchen:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg  -analyzeduration 1000000 -probesize 1000000 -i rtsp://192.168.1.11:554/live/av0?user=admin&passwd=pylecam -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/kitchen
    restart: unless-stopped

  garage:
    image: jrottenberg/ffmpeg:latest
    entrypoint: |
        ffmpeg  -analyzeduration 1000000 -probesize 1000000 -i rtsp://admin:yourmom%21@192.168.1.17:554/videoMain -vcodec copy -acodec copy -f flv rtmp://192.168.1.69/dash/garage
    restart: unless-stopped

  motion:
    build: motion_conf/
    volumes: 
      - /opt/recordings:/recordings
      - ./motion_conf/motion.conf:/etc/motion/motion.conf
      - ./motion_conf/cam_conf:/etc/motion/conf.d
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=America/Chicago
      - TZ=America/Chicago
    restart: unless-stopped

  cctv:
    build: horrible_cctv/
    volumes:
      - ./horrible_cctv:/app
      - /opt/recordings:/recordings
    ports:
      - 81:80
    environment:
      - BASE_URL=http://192.168.1.69/recordings/
      - TIME_OFFSET=5
    restart: unless-stopped
