# chown -R 33:33 config/
# chown -R 33:33 capture/

version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=US/Chicago
      - TZ=America/Chicago
    ports:
      - 80:80
    restart: unless-stopped

  drive_way:
    image: kerberos/kerberos
    volumes:
      - ./capture/drive_way:/etc/opt/kerberosio/capture
      - ./config/drive_way:/etc/opt/kerberosio/config
    ports:
      - 81:80
      - 8901:8889

  frontyard:
    image: kerberos/kerberos
    volumes:
      - ./capture/frontyard:/etc/opt/kerberosio/capture
      - ./config/frontyard:/etc/opt/kerberosio/config
    ports:
      - 82:80
      - 8902:8889

  backyard_porch:
    image: kerberos/kerberos
    volumes:
      - ./capture/backyard_porch:/etc/opt/kerberosio/capture
      - ./config/backyard_porch:/etc/opt/kerberosio/config
    ports:
      - 83:80
      - 8903:8889

  backyard_fence:
    image: kerberos/kerberos
    volumes:
      - ./capture/backyard_fence:/etc/opt/kerberosio/capture
      - ./config/backyard_fence:/etc/opt/kerberosio/config
    ports:
      - 84:80
      - 8904:8889

  kitchen:
    image: kerberos/kerberos
    volumes:
      - ./capture/kitchen:/etc/opt/kerberosio/capture
      - ./config/kitchen:/etc/opt/kerberosio/config
    ports:
      - 85:80
      - 8905:8889

  dining_room:
    image: kerberos/kerberos
    volumes:
      - ./capture/dining_room:/etc/opt/kerberosio/capture
      - ./config/dining_room:/etc/opt/kerberosio/config
    ports:
      - 86:80
      - 8906:8889

  living_room:
    image: kerberos/kerberos
    volumes:
      - ./capture/living_room:/etc/opt/kerberosio/capture
      - ./config/living_room:/etc/opt/kerberosio/config
    ports:
      - 88:80
      - 8908:8889

  garage:
    image: kerberos/kerberos
    volumes:
      - ./capture/garage:/etc/opt/kerberosio/capture
      - ./config/garage:/etc/opt/kerberosio/config
    ports:
      - 89:80
      - 8909:8889
